from django.contrib import admin
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('',views.login),
    path('admin_home',views.admin_home),
    path('add_course',views.add_course),
    path('add_course_post',views.add_course_post),
    path('add_Examcell',views.add_Examcell),
    path('add_Examcell_post',views.add_Examcell_post),
    path('add_Hod',views.add_Hod),
    path('add_hod_post',views.add_hod_post),
    path('add_Subject',views.add_Subject),
    path('add_subject_post',views.add_subject_post),
    path('view_Course',views.view_Course),
    path('delete_course/<id>', views.delete_course),
    path('edit_course/<id>', views.edit_course),
    path('edit_course_post', views.edit_course_post),
    path('view_Examcell',views.view_Examcell),
    path('delete_examcell/<id>',views.delete_examcell),
    path('edit_examcell/<id>',views.edit_examcell),
    path('edit_examcell_post',views.edit_examcell_post),
    path('view_Hod',views.view_Hod),
    path('delete_hod/<id>',views.delete_hod),
    path('edit_hod/<id>',views.edit_hod),
    path('edit_hod_post',views.edit_hod_post),
    path('view_student',views.view_student),
    # path('view_student_post', views.view_student_post),
    path('view_Subject',views.view_Subject),
    path('delete_subject/<id>',views.delete_subject),
    path('edit_subject/<id>', views.edit_subject),
    path('edit_subject_post', views.edit_subject_post),
    path('add_examdetails',views.add_examdetails),
    path('add_examdetails_post', views.add_examdetails_post),
    path('add_Examhall',views.add_Examhall),
    path('add_Examhall_post', views.add_Examhall_post),
    path('add_Examtimetable',views.add_Examtimetable),
    path('add_Examtimetable_post',views.add_Examtimetable_post),
    path('examcell_home',views.Examcell_home),
    path('view_examdetails/<id>',views.view_examdetails),
    path('delete_examdetails/<id>', views.delete_examdetails),
    path('view_examhall',views.view_examhall),
    path('delete_examhall/<id>', views.delete_examhall),
    path('edit_examhall/<id>', views.edit_examhall),
    path('edit_examhall_post', views.edit_examhall_post),
    path('view_examtimetable',views.view_examtimetable),
    path('delete_examtimetable/<id>', views.delete_examtimetable),
    path('edit_examtimetable/<id>', views.edit_examtimetable),
    path('edit_examtimetable_post', views.edit_examtimetable_post),
    path('login_post',views.login_post),
    path('Examcell_home',views.Examcell_home),
    # path('view_examdetails', views.view_examdetails),
    path('view_examhall', views.view_examhall),
    path('view_seatingalloc', views.view_seatingalloc),
    path('hod_home', views.hod_home),
    path('add_hodstudent', views.add_hodstudent),
    path('add_hodstudent_post', views.add_hodstudent_post),
    path('view_hodstudent', views.view_hodstudent),
    path('delete_hodstudent/<id>', views.delete_hodstudent),
    path('edit_hodstudent/<id>', views.edit_hodstudent),
    path('edit_hodstudent_post', views.edit_hodstudent_post),
    path('add_hodstaff', views.add_hodstaff),
    path('add_hodstaff_post', views.add_hodstaff_post),
    path('view_staff', views.view_staff),
    path('edit_staff/<id>', views.edit_staff),
    path('edit_hodstaff_post', views.edit_hodstaff_post),
    path('delete_hodstaff/<id>', views.delete_hodstaff),
    path('add_examduty', views.add_examduty),
    path('add_examduty_post', views.add_examduty_post),
    path('view_examduty/<id>', views.view_examduty),
    path('add_hallarrangement', views.add_hallarrangement),
    path('view_hallarrangement', views.view_hallarrangement),
    # path('add_jobdetails', views.add_jobdetails),
    path('view_jobdetails', views.view_jobdetails),
    path('delete_jobdetails/<id>', views.delete_jobdetails),
    path('view_student/<id>', views.view_student),
    path('logincode', views.logincode),
    path('viewjobdetails', views.viewjobdetails),
    path('viewtimetable', views.viewtimetable),
    path('/viewallocation', views.viewallocation ),
    path('/viewexamdetails', views.viewexamdetails ),
    path('view_examdate', views.view_examdate ),
    path('alumni_registration', views.alumni_registration ),
    path('viewdepartment', views.viewdepartment ),
    path('add_job_details', views.add_job_details ),
    # path('viewaddandmanagejobdetails', views.viewaddandmanagejobdetails ),
    path('view_alumnijobdetails', views.view_alumnijobdetails ),
    path('student_view_alumnijobdetails', views.student_view_alumnijobdetails),
    path('viewchat', views.viewchat),
    path('sendchat', views.sendchat),
    path('view_students_chat', views.view_students_chat),



    path('gentimetable/<id>', views.gentimetable),
    path('generateseat/<d>/<t>/<timetableid>', views.generateseat),
    path('seat', views.seat),
    path('generateseat1', views.generateseat1),
    ]
