# Generated by Django 5.1.4 on 2025-01-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallallocation_table',
            name='EXAMDETAILS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.examdetails_table'),
        ),
        migrations.AlterField(
            model_name='hallallocation_table',
            name='HALL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hall_table'),
        ),
    ]
