# Generated by Django 5.1.4 on 2025-01-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_hallallocation_table_examdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingarrangement_table',
            name='EXAMDETAILS',
        ),
    ]
