# Generated by Django 5.1.4 on 2025-03-12 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_seatingarrangement_table_examdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingarrangement_table',
            name='TIMETABLE',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='myapp.examtimetable_table'),
            preserve_default=False,
        ),
    ]
