# Generated by Django 5.1.4 on 2025-03-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_seatingarrangement_table_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_table',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table'),
            preserve_default=False,
        ),
    ]
