# Generated by Django 5.1.4 on 2025-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alumni_table_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails_table',
            name='jobfile',
            field=models.FileField(upload_to=''),
        ),
    ]
