# Generated by Django 5.1.4 on 2025-03-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_jobdetails_table_jobfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails_table',
            name='ALUMNI',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.alumni_table'),
            preserve_default=False,
        ),
    ]
