# Generated by Django 5.1.4 on 2025-03-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_jobdetails_table_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fn', to='myapp.login_table')),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='myapp.login_table')),
            ],
        ),
    ]
